[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "LLMs_OS"
version = "2.0.0"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
llms-os = "LLMs_OS.cli:main"

[tool.setuptools]
packages = ["LLMs_OS", "LLMs_OS.actions"]
